### ISSUE TITLE
Program stops responding when filtering AH

### ISSUE THREAD

**Issue by NorielSylvire** [clocklear/BagAppraiser#41] opened 2024-04-07 19:24 UTC
**Describe the bug**
The game lags out for multiple seconds, occasionally stops responding and closes, when filtering a lot of items in the auction house.

**To Reproduce**
1. Go to the auction house and open it
2. Select a category with a large number of items, such as "Armor" (without specifying armor type or slot, so that you get all types)
3. (Optional) Add a filter, such as item level between 40 and 50.
4. Lastly, hit search, or select the name/price/ilvl... column to reorder the items and watch your client explode. (jk)

**Expected behavior**
When turning the addon off, this operation occurs successfully in less than a half second, at most, and without causing any lag or freezing the client.

**Additional context**
I am using a large number of addons, but the ones related to the auction house are Auctionator, TSM, TSM-AppHelper and the TSM app.

Also, cool addon. I really wanna keep it :D

**Comment by clocklear** [comment] 2024-04-11 16:03
Thanks for the report. Haven't had a chance to dive into this yet, but will take a look asap. 

Shooting from the hip though, this is puzzling to me as I don't hook into any aspect of the AH for the addon. The only thought I have is that maybe there is a bit of tight-coupling between the AH and the bag events I'm using, in which case perhaps I can add a check for 'am I in the AH right now', in which case we can pause all processing until those operations have ceased.

**Comment by clocklear** [comment] 2024-04-28 00:42
Tried tonight and I can't reproduce this.  I don't have TSM installed though; perhaps that's the actual culprit?

**Comment by clocklear** [comment] 2024-04-30 23:20
Closing this; feel free to reopen if you still experience issues after confirming TSM is not the problem.

**Closed by clocklear** 2024-04-30 23:20 UTC
Labels: bug
